### ISSUE TITLE
[Enhancement][bug] Remove technical blocks from creative tabs

### ISSUE THREAD

**Issue by moechakucha** [paulevsGitch/Creative-b.1.7.3-#1]
These blocks like the halved "bed" caused crashes when my cursor moved onto the icon.
Even if it's one of the problems of the game itself, could you stop listing them so that I don't need to worry about avoiding causing such dumb crashes?
Logs are not available, as I was using MultiMC and forgot to copy the logs.

**Comment by paulevsGitch** [comment]
I don't have crash in dev environment, but these blocks still needs to be removed

![2021-05-21_01 49 44](https://user-images.githubusercontent.com/17707380/119058334-db668100-b9d6-11eb-95b5-75b39170e106.png)

**Comment by paulevsGitch** [comment]
Fixed in 0.1.2
